baseURL: https://daydream.im/
languageCode: en-us
title: Daydream
theme: hugo-fresh
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy 
  description: A Matrix Client written in Rust using WebAssembly.
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/DaydreamLogo_Square.svg
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Fast. Modern.
    # Hero subtitle (optional)
    subtitle: Daydream is a fast and modern Matrix Client purely written in Rust with the power of Webassembly.
    # Button text
    buttontext: Start Chatting
    # Where the main hero button links to
    buttonlink: "https://app.daydream.im"
    # Hero image (from static/images/___)
    image: illustrations/worker.svg
    # Footer logos (from static/images/logos/clients/___.svg)
    #clientlogos:
    #- matrix
    #- tribe
    #- kromo
    #- infinite
    #- gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Source Code
    url: https://github.com/daydream-mx/Daydream
  - title: Matrix.org
    url: https://matrix.org
  #- title: Pricing
  #  url: /
  #- title: Dropdown
  #  sublinks:
  #  - title: Dropdown item
  #    url: /
  #  - title: Dropdown item
  #    url: /
  #  - title: Dropdown item
  #    url: /
  #- title: Log in
  #  url: /
  #- title: Sign up
  #  url: /
  #  button: true
  section1:
    title: Features
    #subtitle: with great responsibility
    tiles:
    - title: Modern Design
      icon: laptop-rocket
      text: We aim to stay modern and sharp with the design
      #url: /
      #buttonText: Free trial
    - title: Good Performance
      icon: laptop-performance
      text: WASM allows to provide a high performance MatrixClient
      #url: /
      #buttonText: Get started
    - title: Open Source
      icon: laptop-github
      text: All Source is publicly available on Github
      url: https://github.com/daydream-mx/Daydream
      buttonText: Get Source
  #section2:
  #  title: You're here because you want the best
  #  subtitle: And we know it
  #  features:
  #  - title: Powerful and unified interface
  #    text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
  #    # Icon (from /images/illustrations/icons/___.svg)
  #    icon: laptop-globe
  #  - title: Cross-device synchronisation
  #    text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
  #    icon: doc-sync
  #  - title: Nomad system
  #    text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
  #    icon: mobile-feed
  section3:
    title: Daydream
    subtitle: The first wasm Matrix Client
    image: illustrations/mockups/app-mockup.png
    buttonText: Start Chatting
    buttonLink: "https://app.daydream.im"
  #section4:
  #  title: Our Clients love us!
  #  subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
  #  clients:
  #  - name: Irma Walters
  #    quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #    job: Accountant
  #    img: 1
  #  - name: John Bradley
  #    quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #    job: Financial Analyst
  #    img: 2
  #  - name: Gary Blackman
  #    quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #    job: HR Manager
  #    img: 3
  section5: false
  footer:
    # Logo (from /images/logos/___)
    logo: DaydreamLogo_Normal Wide.svg
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/daydream-mx/Daydream
      # Icons are from Font Awesome
      icon: github
    bulmalogo: true
    quicklinks:
      column1:
        title: "Product"
        links:
        - text: Discover features
          link: /
        - text: Our roadmap
          link: https://github.com/daydream-mx/Daydream/issues
      #column2:
      #  title: "Blog"
      #  links:
      #  - text: Latest news
      #    link: /blog/
